// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzziqvjfymosjjbzkrma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56emlxdmpmeW1vc2pqYnprcm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjY5NDYsImV4cCI6MjA3MjA0Mjk0Nn0.AnjxfojLyu9DsLqpuCoJicYFoyaIiGbh-lcbydVrvJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});